package com.project_aegis.inventory_service.controller.admin;

import com.project_aegis.inventory_service.dto.campaign.request.CampaignSkuRequest;
import com.project_aegis.inventory_service.dto.campaign.request.CampaignSkuUpdateRequest;
import com.project_aegis.inventory_service.dto.campaign.response.CampaignSkuResponse;
import com.project_aegis.inventory_service.dto.response.ApiResponse;
import com.project_aegis.inventory_service.service.CampaignSkuService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/v1/inventory/admin/campaigns/{campaignId}/skus")
@Tag(name = "Admin Campaign SKUs", description = "Admin APIs for managing SKU allocations within a flash-sale campaign")
public class AdminCampaignSkuController {

    private final CampaignSkuService campaignSkuService;

    @Operation(summary = "Add a SKU with flash price and allocated stock to a DRAFT campaign")
    @PostMapping
    public ResponseEntity<ApiResponse<CampaignSkuResponse>> addSkuToCampaign(
            @PathVariable UUID campaignId,
            @Valid @RequestBody CampaignSkuRequest request) {
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(campaignSkuService.addSkuToCampaign(campaignId, request));
    }

    //campaign sku id is generated by FlashCampaignSku (id) in FlashCampaignSku Table
    @Operation(summary = "Update campaign SKU parameters (flash price, allocated stock, max per user)")
    @PutMapping("/{campaignSkuId}")
    public ResponseEntity<ApiResponse<CampaignSkuResponse>> updateCampaignSku(
            @PathVariable UUID campaignId,
            @PathVariable UUID campaignSkuId,
            @Valid @RequestBody CampaignSkuUpdateRequest request) {
        return ResponseEntity.ok(
                campaignSkuService.updateCampaignSku(campaignId, campaignSkuId, request));
    }
    //campaign sku id is generated by FlashCampaignSku (id) in FlashCampaignSku Table
    @Operation(summary = "Remove a SKU from a campaign  (prohibited once ACTIVE/ENDED)")
    @DeleteMapping("/{campaignSkuId}")
    public ResponseEntity<ApiResponse<Void>> removeSkuFromCampaign(
            @PathVariable UUID campaignId,
            @PathVariable UUID campaignSkuId) {
        return ResponseEntity.ok(
                campaignSkuService.removeSkuFromCampaign(campaignId, campaignSkuId));
    }
}
