spring:
  application:
    name: payment-service
  # enable virtual threads for better performance
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# server & global size limits
server:
  port: ${SERVER_PORT:8085}
  max-http-request-header-size: 16KB
  tomcat:
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
