spring:
  application:
    name: product-service
  # enable virtual threads for better performance
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  profiles:
    active: dev

# global request and header size limits
server:
  max-http-request-header-size: 16KB
  tomcat:
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
